### create schedule
POST http://localhost:8080/schedules
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNAbmF2ZXIuY29tIiwiaWF0IjoxNzA0OTc2NjAyLCJleHAiOjE3MDQ5ODc0MDJ9._wu0LFTpi1efvHq4Oo-KF39ZQRVHDHGeXFvCDgPGZTE"

{
  "contents": "치킨먹으러가기",
  "latitude": 111,
  "locationExplanation": "남부순환로222",
  "longitude": 222,
  "remindAt": "2024-12-25T08:00",
  "scheduleAt": "2024-12-25T11:00",
  "status": "EXIST",
  "title": "치킨모임",
  "scheduleFriendList" : [
    {
      "memberId":"2",
      "name":"조현준"
    },
    {
      "memberId":"3",
      "name":"김나나"
    }
  ]
}