springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs/swagger

spring:
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baselineOnMigrate: true
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
    
cloud:
  aws:
    credentials:
      access-key: ${CLOUD_ACCESS}
      secret-key: ${CLOUD_SECRET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  s3:
    bucket: ${S3_BUCKET}
    folder: ${S3_FOLDER}
    domain: ${S3_DOMAIN}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
