server:
  port: 8087
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs/swagger

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jwt:
    secret: ZeRoBaSe+TeAm+PrOJeCt=DeVhEaVen+KeYwOrD/SeCrEtKeY
  datasource:
    url: jdbc:mariadb://localhost:3307/keyWord
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  flyway:
    enabled: true
    user: root
    password: 1234
    baselineOnMigrate: true
  redis:
    port: 6379
    host: localhost

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: yfmDtQ8a9IaOAcj4s88G
            client-secret: Q9U0K6grRk
            scope:
              - name
              - email
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    
cloud:
  aws:
    credentials:
      access-key: AKIATWDUJVX5R2YGP7KS
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  s3:
    bucket: keyword-img
    folder: keyWord/
    domain: https://d19jzgrojjrozm.cloudfront.net

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
