
name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main","develop" ]
    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Make application.yml
      run : |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.DATABASE_PROPERTIES }}" >> ./src/main/resources/application.yml
        cat ./src/main/resources/application.yml

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
      
    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        container port: 3306
        mariadb version: 'latest'
        character set server: 'utf8'
        mysql database: 'keyWord'
        mysql user: 'keyWord'
        mysql password: ${{ secrets.MARIADB_PASSWORD }}
    - name: check docker ps
      run: |
        CONTAINER_ID=$(docker ps --filter "ancestor=mariadb:latest" --format "{{.ID}}")
        echo "::set-output name=id::$CONTAINER_ID"
    - name: Run Commands in MariaDB Container
      run: |
        CONTAINER_ID=${{ steps.get-container-id.outputs.id }}
        docker exec -it $CONTAINER_ID /bin/bash -c "mysql -u root -p -e 'SHOW DATABASES;'"
        
    - name: grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Wait for MariaDB to start
      run: sleep 15
    - name: Build with Gradle
      run : ./gradlew build --info

    - name: Store Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests/test


            
