
name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main","develop" ]
    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Make application.yml
      run : |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.DATABASE_PROPERTIES }}" >> ./src/main/resources/application.yml
        cat ./src/main/resources/application.yml

    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        host_port: 3307
        container_port: 3306
        character_set_server: 'utf8'
        mariadb_version: '10.6.1'
        mysql_database: 'keyWord'
        mysql_user: 'root'
        mysql_password: ${{ secrets.MARIADB_PASSWORD }}
        
    - name: grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Wait for MariaDB to start
      run: sleep 15
    - name: Build with Gradle
      run : ./gradlew build --info


            
