
name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main","develop" ]
    

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Make application.properties
      run: |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.properties
        echo "${{ secrets.DATABASE_PROPERTIES }}" >> ./src/main/resources/application.properties
        
    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        character set servver: 'utf8'
        mysql database: 'keyword'
        mysql user: 'keyword'
        mysql password: "${{ secrets.MARIADB_PASSWORD }}"
        
    - name: grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run : ./gradlew build


            
